name: ci

on: [push, pull_request]

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run ./ci/fmt.sh
        uses: ./ci/image
        with:
          args: ./ci/fmt.sh

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run ./ci/lint.sh
        uses: ./ci/image
        with:
          args: ./ci/lint.sh

  image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: ./ci/image.sh
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
